version: "3"
services:
  db:
    image: mongo
    restart: always
    container_name: sanggwan-dashboard-mongo
    env_file: .env.mongo
    ports:
      - "27703:27017"
    volumes:
      - "./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh"
